spec: Work around a bug in ctest macro on RHEL 9
Building the RPM package on RHEL 9 failed like this:

    error: /builddir/build/originals/createrepo_c.spec: line 160: Unknown option V in ctest(:-:)

The failure was introduced with commit
c673138669790c970e3147c0d3ec2504ea0b2425 ("spec: Consistently use
CMake RPM macros"). The cause is a bug in a definition of the ctest
macro provided with cmake-rpm-macros-3.26.5-2.el9.noarch by RHEL 9
<https://issues.redhat.com/browse/RHEL-120543>.

This patch works around the bug by redefining the macro while accepting
any options.