Rename "requires" field of cr_Package structure to "requirements"
C++20 added "requires" keyword, breaking inclusion of
createrepo_c/package.h header file as C++ code:

    $ printf '#include <createrepo_c/package.h>\n' | gcc $(pkg-config --cflags createrepo_c) -c -x c++ -
    In file included from <stdin>:1:
    /usr/include/createrepo_c/package.h:118:13: error: expected unqualified-id before ‘requires’
      118 |     GSList *requires;           /*!< requires (list of cr_Dependency structs) */
	  |             ^~~~~~~~

Since we support C++, there is no other way than renaming the
"requires" field of cr_Package structure.

This patch renames it to "requirements".

This patch retains original name in a schema of the SQLite database.
That should allow to reuse it on "crearerepo_c --update" after the
upgrade.

This patch retains the original name next to the new name in Python
binding, not to break Python API.

Because the rename breaks C API, major version of crearerepo_c was bumped.

Because the ABI has not changed, it decouples a shared library's
SONAME from the project version and keep it unchanged. That will save
people from rebuilding applications against the library.

(What this patch does not do is using C11 anonymous union to provide
a backward compatible name next to the new one. It would avoid
C applications from a need to adapt to the new API, yet could break
ABI because compilers are free to add a padding at the end of
a uninon.)

Resolves: #181