Restore compatibility with RPM 4.14.3
Commit 9ff916d5fa738c73bd9ee796d67d29c65b4b7dfb ("Remove uneeded
inclusions of <rpm/rpmlib.h>") broke comptability with RPM before
4.16.0-beta2. Building with 4.14.3 failed:

    /tmp/createrepo_c/src/misc.c:28:10: fatal error: rpm/rpmver.h: No such file or directory
     #include <rpm/rpmver.h>
              ^~~~~~~~~~~~~~
This patch restores a compatibility with older rpm versions. Tested
with rpm-4.14.3.

(In the future, createrepo_c should define a minimal supported RPM
version.)

Relates: #464